server.port=5477

spring.jackson.serialization.write-dates-as-timestamps=false

# Allow large request bodies for up to 10^6 entries
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.codec.max-in-memory-size=50MB
